image: golang:1.17

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test

unit_tests:
  stage: test
  coverage: '/total:\s+\(statements\)\s+(\d+.\d+\%)/'
  script:
    - make unittest

lint_code:
  cache: {}
  image: golangci/golangci-lint:v1.46.2
  stage: test
  before_script:
    - go get mvdan.cc/gofumpt@v0.3.0
  script:
    - golangci-lint run -v
